### ISSUE TITLE
[DOC Bug] - Modify the link to omc to be a working link

### ISSUE THREAD

**Issue by squirrd** [vlours/mg_cluster_status#17]
The link to OMC shared in the README.md is incorrect.
[ "https://github.com/gmeghnag/omc/README.md" ](https://github.com/gmeghnag/omc/README.md)

Should be 
[ "https://github.com/gmeghnag/omc/#readme" ](https://github.com/gmeghnag/omc/#readme)

**Comment by vlours** [comment]
Agree with the link you shared ([https://github.com/gmeghnag/omc/#readme](https://github.com/gmeghnag/omc/#readme)), but not the "title" of your link "https://github.com/gmeghnag/omc/README.md" 😜
